# include "../include/dxf_2D.h"

void hatch :: hatch1()
{
	writeFile << "\n HATCH \n 8 \n 0"
		"\n 62 \n " << color <<
		" \n 370 \n -1 \n 6 \n ByLayer \n 100 \n "
		" AcDbEntity \n 100 \n AcDbHatch";
	hatch_Fill();
}

void hatch :: hatch_Fill()
{
	if (hatch_fill == "SOLID" )
		fill = 1;
	else
		fill = 0;
	if (entityType == "rectangle")
	{
		edges = 4;
		edge_type = 1;
	}
	else
	{
		edges = 1;
		edge_type = 2;
	}

	writeFile << " \n 2 \n " << hatch_fill << 
		" \n 70 \n " << fill << 
		" \n 91 \n 1 \n 92 \n 1"
		" \n 93 \n" << edges << 
		" \n 72 \n " << edge_type <<"\n";
	hatch_entity() ;
	writeFile << " \n 50 \n 0.0 \n 51 \n 360.0 \n "
		" 97 \n 0 \n 52 \n 30 \n 41 \n 1.0 \n ";
}


void hatch :: hatch_entity() 
{
	if(entityType == "rectangle")
	{

		writeFile <<" \n 10 \n " << xStart <<
			" \n 20 \n " << yStart <<
			" \n 11 \n " << xStart <<
			" \n 21 \n " << yEnd <<
			" \n 10 \n " << xStart <<
			" \n 20 \n " << yEnd <<
			" \n 11 \n " << xEnd <<
			" \n 21 \n " << yEnd <<
			" \n 10 \n " << xEnd <<
			" \n 20 \n " << yEnd <<
			" \n 11 \n " << xEnd <<
			" \n 21 \n " << yStart <<
			" \n 10 \n " << xEnd <<
			" \n 20 \n " << yStart <<
			" \n 11 \n " << xStart <<
			" \n 21 \n " << yStart << "\n";
	}
	else
		circle ch;
		ch.write_Input_Part_Entity();
}




